### ISSUE TITLE
[BUG] Filetype CVAT issue

### ISSUE THREAD

**Issue by ctrlsam** [voxel51/fiftyone#2567]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Linux 5.15.81-1-MANJARO
-   **Python version** (`python --version`): Python 3.10.8
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.19.0, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

```python
import fiftyone as fo

dataset = fo.Dataset()
sample = fo.Sample(filepath='some/image/without/filetype')
dataset.add_samples([sample])

dataset.annotate(
  'mytask',
  label_field="new_field",
  label_type="detections",
  classes=["dog", "cat", "person"]
)
```

### Describe the problem
When trying to create a task in CVAT, the job creation will fail to create due to a missing file type extension and the process will indefinitely wait without warning that the filename is invalid, or explanation of the error.
```
 100% |███████████████| 1/1 [8.6ms elapsed, 0s remaining, 117.5 samples/s] 
Computing metadata...
 100% |███████████████| 1/1 [87.8ms elapsed, 0s remaining, 11.4 samples/s] 
Uploading samples to CVAT...
```

If the filename is changed, to have `.jpg` at the end, then the CVAT upload succeeds.

While it seems silly to provide an image without a filetype extension, the user should be informed that the job failed to create due to this.

### Code to reproduce issue

Run the script listed above.

### Other info/logs

The program hangs due to a while loop in the `cvat.py` util file as it cannot locate the job.
```python
# @todo is this loop really needed?
job_ids = []
while not job_ids:
    job_resp = self.get(self.jobs_url(task_id))
    job_ids = [j["id"] for j in job_resp.json()]
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time
