### ISSUE TITLE
[DOCS] Transparency of user tracking

### ISSUE THREAD

**Issue by mzweilin** [voxel51/fiftyone#3553]
### URL(s) with the issue

https://github.com/voxel51/fiftyone/blob/7ee780bc7a4c854371dc9c5facd181517a718d9b/fiftyone/__init__.py#L33C30-L33C30

### Description of proposal (what needs changing)

FiftyOne users are always tracked when running `import fiftyone`, unless we set an environment variable`export FIFTYONE_DISABLE_SERVICES=1`. I don't understand the intention and I didn't find anything from the documentation.

```python
>>> import fiftyone
>>> HTTP Request: POST https://www.google-analytics.com/collect "HTTP/1.1 200 OK"
```

I appreciate the team for contributing a great open-source project to the community, but I think we can do better in protecting users' privacy.

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently
-   [ ] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [x] No. I cannot contribute a documentation fix at this time

**Comment by benjaminpkane** [comment]
Hi @mzweilin. [`FIFTYONE_DO_NOT_TRACK`](https://docs.voxel51.com/user_guide/config.html#configuring-the-app) is a configurable option that will disable all analytics. We certainly respect any and all usage FiftyOne!

**Comment by brimoor** [comment]
To clarify, the *only* thing that is tracked, ever, is an anonymous UUID log when `fiftyone` is imported.

You can disable tracking by setting the `do_not_track` flag of your [FiftyOne config](https://docs.voxel51.com/user_guide/config.html#configuring-fiftyone).
